name: workout_planner
description: A workout plan application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+11

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  confetti: 0.5.5
  url_launcher: 5.5.0
  sqflite: 1.3.0
  path_provider: ^0.5.0+1
  charts_flutter: 0.9.0
  qr_flutter: ^2.0.0+51
  qrcode_reader: 0.4.4
  shared_preferences: ^0.4.2
  package_info: 0.4.0+13
  google_sign_in: 4.0.0
  percent_indicator: ^1.0.13
  cloud_firestore: 0.14.0+1
  connectivity: 0.4.0+1
  rxdart: 0.21.0
  image_gallery_saver: 1.1.0
  permission_handler: 3.0.1
  share: 0.6.5+2
  firebase_auth: 0.18.0+1
  uuid: 2.0.4
  app_review: 1.1.0+1
  apple_sign_in: 0.1.0
  font_awesome_flutter: 8.8.1
  flutter_signin_button: 1.0.0
  keyboard_actions: 3.2.1

  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
  - assets/test.jpg
  - assets/dumbbells.png
  - assets/stopwatch.png
  - assets/dumbbell-48.png
  - assets/dumbbell-96.png
  - assets/chest-96.png
  - assets/muscle-96.png
  - assets/back-96.png
  - assets/leg-96.png
  - assets/abs-96.png
  - database/data.db
  - assets/ic_launcher.png
  - assets/app_icon.png

  fonts:
  - family: Petit
    fonts:
    - asset: fonts/PetitFormalScript-Regular.ttf
  - family: Roboto
    fonts:
    - asset: fonts/Roboto-Regular.ttf
    - asset: fonts/Roboto-Light.ttf
    - asset: fonts/Roboto-Thin.ttf
    - asset: fonts/Roboto-Bold.ttf
  - family: Staa
    fonts:
    - asset: fonts/Staatliches-Regular.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
